server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:29081/railway
spring.datasource.username=root
spring.datasource.password=RyiDnjmwQNDZCUPEeTvcwzxXEysIwNPu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false