server.port=8080

spring.datasource.url=jdbc:postgresql://hoteluser:eBu1d7KvDBCwjarRXDI5LkaUkbfwqFPL@dpg-d6nut07afjfc73ante3g-a.singapore-postgres.render.com/hotel_d3h2
spring.datasource.username=hoteluser
spring.datasource.password=eBu1d7KvDBCwjarRXDI5LkaUkbfwqFPL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false